import 'dart:convert';

import 'package:flutter/foundation.dart';

import '../security/fusion_charts_sanitizer.dart';

/// Version of the Dart to JavaScript envelope understood by this package.
///
/// The bridge JavaScript refuses envelopes carrying any other value, so a
/// package upgrade can never silently talk to a stale cached bridge script.
const int kFusionChartsProtocolVersion = 1;

/// Envelope types sent from Dart into the bridge.
abstract class FusionChartsOutbound {
  static const String render = 'render';
  static const String update = 'update';
  static const String addEvents = 'addEvents';
  static const String removeEvents = 'removeEvents';
  static const String feedData = 'feedData';
  static const String export = 'export';
  static const String dispose = 'dispose';

  static const List<String> all = <String>[
    render,
    update,
    addEvents,
    removeEvents,
    feedData,
    export,
    dispose,
  ];
}

/// Envelope types sent from the bridge back into Dart.
abstract class FusionChartsInbound {
  static const String ready = 'ready';
  static const String event = 'event';
  static const String error = 'error';

  /// Carries an export payload captured inside the page.
  static const String export = 'export';

  static const List<String> all = <String>[ready, event, error, export];
}

/// Raised when a message fails validation at the bridge boundary.
///
/// The message deliberately carries no payload contents so that a malformed
/// data source or license key can never reach a log through an exception.
class FusionChartsProtocolError implements Exception {
  FusionChartsProtocolError(this.reason);

  final String reason;

  @override
  String toString() => 'FusionChartsProtocolError: $reason';
}

/// A single versioned bridge envelope.
///
/// Every user-controlled value travels inside [payload] and is serialised with
/// [jsonEncode]. No caller may build JavaScript source by interpolation.
class FusionChartsMessage {
  FusionChartsMessage({
    required this.type,
    required this.chartId,
    this.requestId,
    Map<String, dynamic>? payload,
    this.protocolVersion = kFusionChartsProtocolVersion,
  }) : payload = payload ?? const <String, dynamic>{};

  final String type;
  final String chartId;
  final String? requestId;
  final Map<String, dynamic> payload;
  final int protocolVersion;

  /// Maximum serialised envelope size accepted in either direction.
  ///
  /// Oversized payloads are rejected in Dart rather than being handed to the
  /// platform WebView, where the failure mode is a silent truncation.
  static const int maxEncodedLength = 8 * 1024 * 1024;

  /// Chart IDs are generated by this package, never by the caller. The pattern
  /// is enforced anyway so a future public API cannot widen it by accident.
  static final RegExp _chartIdPattern = RegExp(r'^fc-[A-Za-z0-9_-]{1,64}$');

  /// FusionCharts event names are alphanumeric. Rejecting anything else keeps
  /// quotes and separators out of the registration path.
  static final RegExp _eventNamePattern =
      RegExp(r'^[A-Za-z][A-Za-z0-9_]{0,63}$');

  static bool isValidChartId(String value) => _chartIdPattern.hasMatch(value);

  static bool isValidEventName(String value) =>
      _eventNamePattern.hasMatch(value);

  /// The payload with every network-capable export key removed.
  ///
  /// Sanitising here rather than at each call site makes this the single
  /// chokepoint for outbound chart configuration: `render`, `update` and
  /// `FusionChartsController.setData` all serialise through it, and a future
  /// entry point cannot forget to sanitise.
  Map<String, dynamic> sanitizedPayload() {
    final Object? source = payload['dataSource'];
    if (source is! Map) {
      return payload;
    }
    final List<String> stripped = <String>[];
    final Map<String, dynamic> safe = sanitizeDataSource(
      Map<String, dynamic>.from(source),
      onStripped: stripped.add,
    );
    if (stripped.isNotEmpty) {
      assert(() {
        // Key paths only. A value here could be a credential planted in a
        // hostile configuration, and this reaches the application's log.
        debugPrint('[fusioncharts] removed network-capable export keys from '
            'dataSource: ${stripped.join(', ')}');
        return true;
      }());
    }
    final Map<String, dynamic> out = Map<String, dynamic>.from(payload);
    out['dataSource'] = safe;
    return out;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> json = <String, dynamic>{
      'protocolVersion': protocolVersion,
      'chartId': chartId,
      'type': type,
      'payload': sanitizedPayload(),
    };
    if (requestId != null) {
      json['requestId'] = requestId;
    }
    return json;
  }

  /// Serialises this envelope, validating it first.
  ///
  /// Throws [FusionChartsProtocolError] rather than emitting a message the
  /// bridge would have to reject at the far end.
  String encode() {
    if (!FusionChartsOutbound.all.contains(type)) {
      throw FusionChartsProtocolError('unknown outbound type "$type"');
    }
    if (!isValidChartId(chartId)) {
      throw FusionChartsProtocolError('invalid chart id');
    }
    if (protocolVersion != kFusionChartsProtocolVersion) {
      throw FusionChartsProtocolError(
          'unsupported protocol version $protocolVersion');
    }
    final String encoded = jsonEncode(toJson());
    if (encoded.length > maxEncodedLength) {
      throw FusionChartsProtocolError(
          'payload exceeds $maxEncodedLength bytes');
    }
    return encoded;
  }

  /// Parses an inbound envelope received over the JavaScript channel.
  ///
  /// Inbound text is untrusted: it arrives from a page that may be running
  /// third-party chart code, so every field is checked before use.
  static FusionChartsMessage decodeInbound(String raw) {
    if (raw.length > maxEncodedLength) {
      throw FusionChartsProtocolError('inbound message too large');
    }

    Object? decoded;
    try {
      decoded = jsonDecode(raw);
    } catch (_) {
      throw FusionChartsProtocolError('inbound message is not valid JSON');
    }

    if (decoded is! Map) {
      throw FusionChartsProtocolError('inbound message is not an object');
    }

    final Object? version = decoded['protocolVersion'];
    if (version != kFusionChartsProtocolVersion) {
      throw FusionChartsProtocolError('unsupported inbound protocol version');
    }

    final Object? type = decoded['type'];
    if (type is! String || !FusionChartsInbound.all.contains(type)) {
      throw FusionChartsProtocolError('unknown inbound type');
    }

    final Object? chartId = decoded['chartId'];
    if (chartId is! String || !isValidChartId(chartId)) {
      throw FusionChartsProtocolError('invalid inbound chart id');
    }

    final Object? requestId = decoded['requestId'];
    if (requestId != null && requestId is! String) {
      throw FusionChartsProtocolError('invalid request id');
    }

    final Object? payload = decoded['payload'];
    if (payload != null && payload is! Map) {
      throw FusionChartsProtocolError('invalid payload');
    }

    return FusionChartsMessage(
      type: type,
      chartId: chartId,
      requestId: requestId as String?,
      payload: payload == null
          ? const <String, dynamic>{}
          : Map<String, dynamic>.from(payload as Map),
    );
  }
}
