import 'dart:convert';
import 'dart:developer';
import 'dart:io';
import 'dart:typed_data';
import 'package:flutter/material.dart';
import 'package:flutter_fusioncharts/src/utils/permission_manager.dart';
import 'package:flutter_inappwebview/flutter_inappwebview.dart';

class DownloadingDialog extends StatefulWidget {
  final String fileName;
  final DownloadStartRequest request;

  const DownloadingDialog(
      {Key? key, required this.fileName, required this.request})
      : super(key: key);

  @override
  _DownloadingDialogState createState() => _DownloadingDialogState();
}

class _DownloadingDialogState extends State<DownloadingDialog> {
  late Uint8List base64decode;

  late String fileName;

  var data;

  @override
  void initState() {
    // CSV and XLSX
    // url: blob:null/ddd3a28a-8826-4901-a030-d5cc172d5a1c,

    super.initState();
    decode();
    saveFile();
  }

  decode() {
    fileName = widget.request.suggestedFilename.toString().split('.')[1];
    if (fileName == 'svg' ||
        fileName == 'png' ||
        fileName == 'jpg' ||
        fileName == 'pdf') {
      base64decode =
          base64.decode(widget.request.url.toString().split(';base64,')[1]);
    } else {
      base64decode = base64.decode(widget.request.url.toString().split('/')[1]);
    }

    // base64decode = base64.decode(widget.request.url.toString().split(',')[1]);

    // base64decode = base64Decode('MSwiRWxkb24gQmFzZSBmb3Igc3RhY2thYmxlIHN0b3JhZ2Ugc2hlbGYsIHBsYXRpbnVtIixNdWhhbW1lZCBNYWNJbnR5cmUsMywtMjEzLjI1LDM4Ljk0LDM1LE51bmF2dXQsU3RvcmFnZSAmIE9yZ2FuaXphdGlvbiwwLjgKMiwiMS43IEN1YmljIEZvb3QgQ29tcGFjdCAiIkN1YmUiIiBPZmZpY2UgUmVmcmlnZXJhdG9ycyIsQmFycnkgRnJlbmNoLDI5Myw0NTcuODEsMjA4LjE2LDY4LjAyLE51bmF2dXQsQXBwbGlhbmNlcywwLjU4CjMsIkNhcmRpbmFsIFNsYW50LUTvv70gUmluZyBCaW5kZXIsIEhlYXZ5IEdhdWdlIFZpbnlsIixCYXJyeSBGcmVuY2gsMjkzLDQ2LjcxLDguNjksMi45OSxOdW5hdnV0LEJpbmRlcnMgYW5kIEJpbmRlciBBY2Nlc3NvcmllcywwLjM5CjQsUjM4MCxDbGF5IFJvemVuZGFsLDQ4MywxMTk4Ljk3LDE5NS45OSwzLjk5LE51bmF2dXQsVGVsZXBob25lcyBhbmQgQ29tbXVuaWNhdGlvbiwwLjU4CjUsSG9sbWVzIEhFUEEgQWlyIFB1cmlmaWVyLENhcmxvcyBTb2x0ZXJvLDUxNSwzMC45NCwyMS43OCw1Ljk0LE51bmF2dXQsQXBwbGlhbmNlcywwLjUKNixHLkUuIExvbmdlci1MaWZlIEluZG9vciBSZWNlc3NlZCBGbG9vZGxpZ2h0IEJ1bGJzLENhcmxvcyBTb2x0ZXJvLDUxNSw0LjQzLDYuNjQsNC45NSxOdW5hdnV0LE9mZmljZSBGdXJuaXNoaW5ncywwLjM3CjcsIkFuZ2xlLUQgQmluZGVycyB3aXRoIExvY2tpbmcgUmluZ3MsIExhYmVsIEhvbGRlcnMiLENhcmwgSmFja3Nvbiw2MTMsLTU0LjA0LDcuMyw3LjcyLE51bmF2dXQsQmluZGVycyBhbmQgQmluZGVyIEFjY2Vzc29yaWVzLDAuMzgKOCwiU0FGQ08gTW9iaWxlIERlc2sgU2lkZSBGaWxlLCBXaXJlIEZyYW1lIixDYXJsIEphY2tzb24sNjEzLDEyNy43MCw0Mi43Niw2LjIyLE51bmF2dXQsU3RvcmFnZSAmIE9yZ2FuaXphdGlvbiwKOSwiU0FGQ08gQ29tbWVyY2lhbCBXaXJlIFNoZWx2aW5nLCBCbGFjayIsTW9uaWNhIEZlZGVybGUsNjQzLC02OTUuMjYsMTM4LjE0LDM1LE51bmF2dXQsU3RvcmFnZSAmIE9yZ2FuaXphdGlvbiwKMTAsWGVyb3ggMTk4LERvcm90aHkgQmFkZGVycyw2NzgsLTIyNi4zNiw0Ljk4LDguMzMsTnVuYXZ1dCxQYXBlciwwLjM4Cg==');
    // base64decode = base64Decode('0M8R4KGxGuEAAAAAAAAAAAAAAAAAAAAAOwADAP7/CQAGAAAAAAAAAAAAAAABAAAADgAAAAAAAAAAEAAACwAAAAEAAAD+////AAAAAAAAAAD////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////9/////////wMAAAAEAAAABQAAAAYAAAAHAAAACAAAAAkAAAAKAAAA/v////7///8NAAAA/v///w8AAAD+/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////1IAbwBvAHQAIABFAG4AdAByAHkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWAAUA////////////////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/v///wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD///////////////8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD+////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP///////////////wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP7///8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA////////////////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/v///wAAAAAAAAAACQgQAAAGBQC7DcwHAAAAAAYAAADhAAIAsATBAAIAAADiAAAAXABwAAQAAENhbGMgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICBCAAIAsARhAQIAAADAAQAAPQECAAEAnAACAA4ArwECAAAAvAECAAAAPQASAAAAAAAAQAAgOAAAAAAAAQDNAEAAAgAAAI0AAgAAACIAAgAAAA4AAgABALcBAgAAANoAAgAAADEAGgDIAAAA/3+QAQAAAAIAAAUBQQByAGkAYQBsADEAGgDIAAAA/3+QAQAAAAAAAAUBQQByAGkAYQBsADEAGgDIAAAA/3+QAQAAAAAAAAUBQQByAGkAYQBsADEAGgDIAAAA/3+QAQAAAAAAAAUBQQByAGkAYQBsADEAGgDIAAAA/3+8AgAAAAIAAAUBQQByAGkAYQBsAB4EDACkAAcAAEdFTkVSQUweBA0ApQAIAABNTS9ERC9ZWeAAFAAAAKQA9f8gAAAAAAAAAAAAAADAIOAAFAABAAAA9f8gAAD0AAAAAAAAAADAIOAAFAABAAAA9f8gAAD0AAAAAAAAAADAIOAAFAACAAAA9f8gAAD0AAAAAAAAAADAIOAAFAACAAAA9f8gAAD0AAAAAAAAAADAIOAAFAAAAAAA9f8gAAD0AAAAAAAAAADAIOAAFAAAAAAA9f8gAAD0AAAAAAAAAADAIOAAFAAAAAAA9f8gAAD0AAAAAAAAAADAIOAAFAAAAAAA9f8gAAD0AAAAAAAAAADAIOAAFAAAAAAA9f8gAAD0AAAAAAAAAADAIOAAFAAAAAAA9f8gAAD0AAAAAAAAAADAIOAAFAAAAAAA9f8gAAD0AAAAAAAAAADAIOAAFAAAAAAA9f8gAAD0AAAAAAAAAADAIOAAFAAAAAAA9f8gAAD0AAAAAAAAAADAIOAAFAAAAAAA9f8gAAD0AAAAAAAAAADAIOAAFAAAAKQAAQAgAAAAAAAAAAAAAADAIOAAFAABACsA9f8gAADwAAAAAAAAAADAIOAAFAABACkA9f8gAADwAAAAAAAAAADAIOAAFAABACwA9f8gAADwAAAAAAAAAADAIOAAFAABACoA9f8gAADwAAAAAAAAAADAIOAAFAABAAkA9f8gAADwAAAAAAAAAADAIOAAFAAFAKQAAQAgAAAIAAAAAAAAAADAIOAAFAAAAKUAAQAgAAAMAAAAAAAAAADAIOAAFAAAAKQAAQAgAAAIAAAAAAAAAADAIJMCBAAAgAD/kwIEABCAA/+TAgQAEYAG/5MCBAASgAT/kwIEABOAB/+TAgQAFIAF/2ABAgABAIUADgAiBgAAAAAGAFNoZWV0MYwABAABAAEAwQEIAMEBAABUjQEA6wBaAA8AAPBSAAAAAAAG8BgAAAAABAAAAgAAAAEAAAABAAAAAQAAAAEAAAAzAAvwEgAAAL8ACAAIAIEBCQAACMABQAAACEAAHvEQAAAADQAACAwAAAgXAAAI9wAAEPwASAE0AAAAIQAAAAoAAEZpcnN0IE5hbWUJAABMYXN0IE5hbWUGAABHZW5kZXIHAABDb3VudHJ5AwAAQWdlBAAARGF0ZQIAAElkBQAARHVsY2UFAABBYnJpbAYAAEZlbWFsZQ0AAFVuaXRlZCBTdGF0ZXMKAAAxNS8xMC8yMDE3BAAATWFyYQkAAEhhc2hpbW90bw0AAEdyZWF0IEJyaXRhaW4KAAAxNi8wOC8yMDE2BgAAUGhpbGlwBAAAR2VudAQAAE1hbGUGAABGcmFuY2UKAAAyMS8wNS8yMDE1CAAAS2F0aGxlZW4GAABIYW5uZXIHAABOZXJlaWRhBwAATWFnd29vZAYAAEdhc3RvbgUAAEJydW1tBAAARXR0YQQAAEh1cm4HAABFYXJsZWFuBgAATWVsZ2FyCAAAVmluY2VuemEHAABXZWlsYW5k/wAKACEAtwQAAAwAAABjCBUAYwgAAAAAAAAAAAAAFQAAAAAAAAACCgAAAAkIEAAABhAAuw3MBwAAAAAGAAAADAACAGQADwACAAEAEQACAAAAEAAIAPyp8dJNYlA/XwACAAEAgAAIAAAAAAAAAAAAJQIEAAAAAAGBAAIAwQQqAAIAAAArAAIAAACCAAIAAQAUACQAIQAAJkMmIlRpbWVzIE5ldyBSb21hbixSZWd1bGFyIiYxMiZBFQApACYAACZDJiJUaW1lcyBOZXcgUm9tYW4sUmVndWxhciImMTJQYWdlICZQgwACAAAAhAACAAAAJgAIADMzMzMzM+k/JwAIADMzMzMzM+k/KAAIAIMt2IIt2PA/KQAIAIMt2IIt2PA/oQAiAAkAZAABAAEAAQCCACwBLAEzMzMzMzPpPzMzMzMzM+k/AQBVAAIACgB9AAwAAAAAAYgLDwAAAAAAAAIOAAAAAAALAAAAAAAIAAAACAIQAAAAAAAIAAABAAAAAIABFQAIAhAAAQAAAAgAAAEAAAAAAAEPAAgCEAACAAAACAAAAQAAAAAAAQ8ACAIQAAMAAAAIAAABAAAAAAABDwAIAhAABAAAAAgAAAEAAAAAAAEPAAgCEAAFAAAACAAAAQAAAAAAAQ8ACAIQAAYAAAAIAAABAAAAAAABDwAIAhAABwAAAAgAAAEAAAAAAAEPAAgCEAAIAAAACAAAAQAAAAAAAQ8ACAIQAAkAAAAIAAABAAAAAAABDwAIAhAACgAAAAAAJQEAAAAAAAEPAAgCEAALAAAAAAAlAQAAAAAAAQ8ACAIQAAwAAAAAACUBAAAAAAABDwAIAhAADQAAAAAAJQEAAAAAAAEPAAgCEAAOAAAAAAAlAQAAAAAAAQ8ACAIQAA8AAAAAACUBAAAAAAABDwAIAhAAEAAAAAAAJQEAAAAAAAEPAAgCEAARAAAAAAAlAQAAAAAAAQ8ACAIQABIAAAAAACUBAAAAAAABDwAIAhAAEwAAAAAAJQEAAAAAAAEPAAgCEAAUAAAAAAAlAQAAAAAAAQ8ACAIQABUAAAAAACUBAAAAAAABDwAIAhAAFgAAAAAAJQEAAAAAAAEPAAgCEAAXAAAAAAAlAQAAAAAAAQ8ACAIQABgAAAAAACUBAAAAAAABDwAIAhAAGQAAAAAAJQEAAAAAAAEPAAgCEAAaAAAAAAAlAQAAAAAAAQ8ACAIQABsAAAAAACUBAAAAAAABDwAIAhAAHAAAAAAAJQEAAAAAAAEPAAgCEAAdAAAAAAAlAQAAAAAAAQ8ACAIQAB4AAAAAACUBAAAAAAABDwAIAhAAHwAAAAAAJQEAAAAAAAEPAAgCEAAgAAAAAAAlAQAAAAAAAQ8ACAIQACEAAAAAACUBAAAAAAABDwAIAhAAIgAAAAAAJQEAAAAAAAEPAAgCEAAjAAAAAAAlAQAAAAAAAQ8ACAIQACQAAAAAACUBAAAAAAABDwAIAhAAJQAAAAAAJQEAAAAAAAEPAAgCEAAmAAAAAAAlAQAAAAAAAQ8ACAIQACcAAAAAACUBAAAAAAABDwAIAhAAKAAAAAAAJQEAAAAAAAEPAAgCEAApAAAAAAAlAQAAAAAAAQ8ACAIQACoAAAAAACUBAAAAAAABDwAIAhAAKwAAAAAAJQEAAAAAAAEPAAgCEAAsAAAAAAAlAQAAAAAAAQ8ACAIQAC0AAAAAACUBAAAAAAABDwAIAhAALgAAAAAAJQEAAAAAAAEPAAgCEAAvAAAAAAAlAQAAAAAAAQ8ACAIQADAAAAAAACUBAAAAAAABDwAIAhAAMQAAAAAAJQEAAAAAAAEPAAgCEAAyAAAAAAAlAQAAAAAAAQ8AfgIKAAAAAAAVAAIAAAD9AAoAAAABABUAAAAAAP0ACgAAAAIAFQABAAAA/QAKAAAAAwAVAAIAAAD9AAoAAAAEABUAAwAAAP0ACgAAAAUAFQAEAAAA/QAKAAAABgAVAAUAAAD9AAoAAAAHABUABgAAAH4CCgABAAAADwAGAAAA/QAKAAEAAQAPAAcAAAD9AAoAAQACAA8ACAAAAP0ACgABAAMADwAJAAAA/QAKAAEABAAPAAoAAAB+AgoAAQAFAA8AggAAAP0ACgABAAYAFgALAAAAfgIKAAEABwAPAGoYAAB+AgoAAgAAAA8ACgAAAP0ACgACAAEADwAMAAAA/QAKAAIAAgAPAA0AAAD9AAoAAgADAA8ACQAAAP0ACgACAAQADwAOAAAAfgIKAAIABQAPAGYAAAD9AAoAAgAGAA8ADwAAAH4CCgACAAcADwC6GAAAfgIKAAMAAAAPAA4AAAD9AAoAAwABAA8AEAAAAP0ACgADAAIADwARAAAA/QAKAAMAAwAPABIAAAD9AAoAAwAEAA8AEwAAAH4CCgADAAUADwCSAAAA/QAKAAMABgAPABQAAAB+AgoAAwAHAA8AbigAAH4CCgAEAAAADwASAAAA/QAKAAQAAQAPABUAAAD9AAoABAACAA8AFgAAAP0ACgAEAAMADwAJAAAA/QAKAAQABAAXAAoAAAB+AgoABAAFAA8AZgAAAP0ACgAEAAYAFgALAAAAfgIKAAQABwAPAHY3AAB+AgoABQAAAA8AFgAAAP0ACgAFAAEADwAXAAAA/QAKAAUAAgAPABgAAAD9AAoABQADAA8ACQAAAP0ACgAFAAQAFwAKAAAAfgIKAAUABQAPAOoAAAD9AAoABQAGAA8ADwAAAH4CCgAFAAcADwCSJgAAfgIKAAYAAAAPABoAAAD9AAoABgABAA8AGQAAAP0ACgAGAAIADwAaAAAA/QAKAAYAAwAXABIAAAD9AAoABgAEABcACgAAAH4CCgAGAAUADwBiAAAA/QAKAAYABgAPABQAAAB+AgoABgAHAA8A6icAAH4CCgAHAAAADwAeAAAA/QAKAAcAAQAPABsAAAD9AAoABwACAA8AHAAAAP0ACgAHAAMADwAJAAAA/QAKAAcABAAPAA4AAAB+AgoABwAFAA8A4gAAAP0ACgAHAAYAFgALAAAAfgIKAAcABwAPADo4AAB+AgoACAAAAA8AIgAAAP0ACgAIAAEADwAdAAAA/QAKAAgAAgAPAB4AAAD9AAoACAADAA8ACQAAAP0ACgAIAAQAFwAKAAAAfgIKAAgABQAPAG4AAAD9AAoACAAGAA8ADwAAAH4CCgAIAAcADwBiJgAAfgIKAAkAAAAPACYAAAD9AAoACQABAA8AHwAAAP0ACgAJAAIADwAgAAAA/QAKAAkAAwAPAAkAAAD9AAoACQAEABcACgAAAH4CCgAJAAUADwCiAAAA/QAKAAkABgAPABQAAAB+AgoACQAHAA8AUmYAAOwAUAAPAALwSAAAABAACPAIAAAAAQAAAAAEAAAPAAPwMAAAAA8ABPAoAAAAAQAJ8BAAAAAAAAAAAAAAAAAAAAAAAAAAAgAK8AgAAAAABAAABQAAAD4CEgC2BgAAAABAAAAAAAAAAAAAAAAdAA8AAxEACgAAAAEAEQARAAoKZwgXAGcIAAAAAAAAAAAAAAIAAf////8AAAAACgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAP7////+////BAAAAAUAAAAGAAAABwAAAP7///8JAAAA/v////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////8BAP7/AwoAAP////8QCAIAAAAAAMAAAAAAAABGGwAAAE1pY3Jvc29mdCBFeGNlbCA5Ny1UYWJlbGxlAAYAAABCaWZmOAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD+/wAAAQACAAAAAAAAAAAAAAAAAAAAAAABAAAA4IWf8vlPaBCrkQgAKyez2TAAAAAIAQAADQAAAAEAAABwAAAAAgAAAHgAAAADAAAAhAAAAAQAAACQAAAABQAAAJwAAAAGAAAAqAAAAAcAAAC0AAAACAAAAMAAAAAJAAAAzAAAAAoAAADYAAAACwAAAOQAAAAMAAAA8AAAAA0AAAD8AAAAAgAAAOn9AAAeAAAAAQAAAAAAAAAeAAAAAQAAAAAAAAAeAAAAAQAAAAAAAAAeAAAAAQAAAAAAAAAeAAAAAQAAAAAAAAAeAAAAAQAAAAAAAAAeAAAAAQAAAAAAAAAeAAAAAgAAADQAAABAAAAAgN8YwsQAAABAAAAAAAAAAAAAAABAAAAALFw68z0M0wFAAAAAY/Ou8gMN0wEAAAAAAAAAAP7/AAABAAIAAAAAAAAAAAAAAAAAAAAAAAIAAAAC1c3VnC4bEJOXCAArLPmuRAAAAAXVzdWcLhsQk5cIACss+a5cAAAAGAAAAAEAAAABAAAAEAAAAAIAAADp/QAAGAAAAAEAAAABAAAAEAAAAAIAAADp/QAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAUgBvAG8AdAAgAEUAbgB0AHIAeQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABYABQD//////////wEAAAAQCAIAAAAAAMAAAAAAAABGAAAAAAAAAAAAAAAAAAAAAAAAAAAMAAAAgAIAAAAAAABXAG8AcgBrAGIAbwBvAGsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEgACAAIAAAAEAAAA/////wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAABdEAAAAAAAAAEAQwBvAG0AcABPAGIAagAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAASAAIAAwAAAP//////////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEkAAAAAAAAAAQBPAGwAZQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAoAAgD///////////////8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAFAAAAAAAAAAFAFMAdQBtAG0AYQByAHkASQBuAGYAbwByAG0AYQB0AGkAbwBuAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKAACAP////8FAAAA/////wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMAAAA4AQAAAAAAAAUARABvAGMAdQBtAGUAbgB0AFMAdQBtAG0AYQByAHkASQBuAGYAbwByAG0AYQB0AGkAbwBuAAAAAAAAAAAAAAA4AAIA////////////////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAHQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD///////////////8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD+////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP///////////////wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP7///8AAAAAAAAAAA==');
  }

  saveFile() async {
    data = await File(
            '${PermissionManager().directory!.absolute.path}.${widget.fileName}.$fileName')
        .writeAsBytes(base64decode);
    // File('${PermissionManager().directory!.absolute.path}.${widget.fileName}dfff.xls').writeAsBytesSync(base64decode,flush: true);
    print(data);
    setState(() {});
  }

  @override
  Widget build(BuildContext context) {
    return AlertDialog(
      backgroundColor: Colors.black,
      content: Column(
        mainAxisSize: MainAxisSize.min,
        children: [
          Row(
            mainAxisAlignment: MainAxisAlignment.end,
            children: [
              IconButton(
                  onPressed: () {
                    Navigator.pop(context);
                  },
                  icon: const Icon(
                    Icons.close_outlined,
                    color: Colors.white,
                  ))
            ],
          ),
          const SizedBox(
            height: 20,
          ),
          data == null
              ? const CircularProgressIndicator.adaptive()
              : const Text(
                  'Downloaded',
                  style: TextStyle(color: Colors.white),
                ),
          const SizedBox(
            height: 20,
          ),
          // base64decode==null?const CircularProgressIndicator.adaptive():SizedBox(child: Image.memory(base64decode),)
        ],
      ),
    );
  }
}
